### PR TITLE
Update route.php to support php 8.1

### PR DESCRIPTION
**Pull request by Pok4**
I update this to make the custom parameters work on php 8.1

Without this modification custom parameters not working on php 8.1, please make the changes :)

PS: As i said, the changes is for 1.2.0 alpha

### CODE REVIEW

**Comment by Pok4** [comment]
The changes are for 1.2alpha

`call_user_func_array(array($instance, $this->action), $this->parameters);`

-->

`call_user_func_array(array($instance, $this->action), array_values($this->parameters));`

**Comment by Pok4** [comment]
I get a second error: PHP Warning: in file C:/xampp2/htdocs/vendor/dannyvankooten/php-router/src/Router.php on line 124: preg_match_all(): Compilation failed: invalid range in character class at offset 5

They already make a changes - https://github.com/dannyvankooten/PHP-Router/pull/127

i already edit the files with this changes, i tested everything on php 8.1 and its working...

Please, make the changes to the repo.. I'm completely newbie with github, this is my first pull request...
